version: '3'
services:
  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch-node
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true  # Optional: disable auth for testing
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600" # metrics port

volumes:
  opensearch-data:
